### ISSUE TITLE
Canvas name error in generator

### ISSUE THREAD

**Issue by freeman-lab** [sethvincent/generator-crtrdg#2]
Very minor issue, but I think this commit (https://github.com/sethvincent/generator-crtrdg/commit/ef8e528f27ae97a1d44c299f82d93ef178ab1439) may not be in the published version of the generator. 

When I do a clean

```
npm install generator-crtrdg -g
```

And then

```
yo crtrdg
```

There's still a `canvasId: 'game'` instead of `canvas: 'game'` in the resulting `game.js`.

Otherwise the generator works great. And this is super cool project, we're excited to start playing with it and hopefully contribute!

**Comment by sethvincent** [comment]
Wow sorry I just noticed this. New version published!
